// ============================================================================
// Opens a customer/supplier's WhatsApp chat, preferring WhatsApp Business on
// Android.
//
// A WebView (which is all a Capacitor app's UI really is) has no way to pick
// one specific app to handle a link — that's only possible through a real
// Android Intent with setPackage(), which requires native code. This calls
// into WhatsAppPlugin.java (generated by .github/workflows/build-apk.yml,
// the same way StorageAccessPlugin.java is — see nativeFileSave.js), which
// opens WhatsApp Business directly if it's installed, falling back to
// regular WhatsApp, then to the OS's own app-picker.
//
// Web, iOS, and the Windows/Electron build have no such native layer, so
// they always just use the plain wa.me link.
// ============================================================================

import { Capacitor, registerPlugin } from "@capacitor/core";

const WhatsApp = registerPlugin("WhatsApp");

export async function openWhatsApp(phone) {
  const digits = (phone || "").replace(/[^0-9]/g, "");
  if (!digits) return;

  if (Capacitor.getPlatform() === "android") {
    try {
      await WhatsApp.open({ phone: digits });
      return;
    } catch (e) {
      // Falls through to the wa.me link below.
    }
  }

  window.location.href = `https://wa.me/${digits}`;
}
